#! This file is for the set up of xxx_med_to_csv program.
#* Three types of parameters:
#   - "infos_col" : for 1 column output 
#   - "infos_lab" : for labelled output
#   - "infos_opt" : for further options
#* You need to indicate the information in this format:
#   Keys : values , where : 
#       - Keys are the column names that you want in the output file
#       - Values are, for infos_col: row number - 1 (Start index :0)
#                     for infos_lab: letters used in medAssociate exercise
#                     for infos_opt: 
#! Warning to get a global array in a var set your key as :
#  Key : ["LETTER", first-index (start at 0), "number to last index"]
#     example:  my_key : ["Z", 0, 120]
#     Note: If the last index is the end of the array, write "end" instead of the number
#     example: my_key : ["Z", 0, "end"]
#* cut and eval Keys are special keys
# - cut: for cutting an output on a special character usually a dot into 2 columns :
#     The value must be a list of list of 4 elements :
#           - key to cut
#           - separator generaly the dot character
#           - Col names of first sub-element
#           - Col names of second sub-element
# - eval: for some column must be the result of a Python command line. It's necessarly a python
#         dictionnary with Key as column name and value a short command line as a string.
# For example this option can be used to get information in path (see examples below)
#* The following Keys are med associate keywords only usable with labelled file :
#   - Start Date
#   - End Date
#   - Subject
#   - Experiment
#   - Group
#   - Box
#   - Start Time
#   - End Time
#   - MSN: Medassociate exercice names
#! Notes: Start Date and Start Time are automaticaly added to the results.

#Here are two templates with examples
infos_col:
  subject: 6
  box: 9
  delay: 66
  step_at_endsess: 73
  sk_dur_at_endsess: 88
  reinforced_resp: 90
  reinforcers: 91
  res_during_reward_deliv: 92
  to_resp: 93
  delivery_s: 94
  to_s: 95
  shock_s: 96
  resets_number: 97
  reinforcers_max_sk_dur: 98
  mn_left_non_resp: 99
  resp_cur_sk_dur: 100
  final_sk_dur: 101
  base_value: [120,"end"]
infos_lab:
  subject: "Subject"
  box: "Box"
  delay: "B"
  step_at_endsess: "I"
  sk_dur_at_endsess: "X"
  reinforced_resp: ["Z", 0]
  reinforcers: ["Z", 1]
  res_during_reward_deliv: ["Z", 2]
  to_resp: ["Z", 3]
  delivery_s: ["Z", 4]
  to_s: ["Z", 5]
  shock_s: ["Z", 6]
  resets_number: ["Z", 7]
  reinforcers_max_sk_dur: ["Z", 8]
  mn_left_non_resp: ["Z", 9]
  resp_cur_sk_dur: ["Z", 10]
  final_sk_dur: ["Z", 11]
  base_value: ["Z", 30, "end"]

options:
  remove_zero_ending: True #Or False
  cut : [["base_value", ".", "time_stamp", "shock_step"]]
  eval: {"prog":"path_file.split('/')[-1]"}
